#######################################################################################
# Book settings
title : Kicking the Tires on Jupyter-Book # The title of the book. Will be placed in the left navbar.
author: Ryan Lowe   # The author of the book
# logo: 'qe-logo-large.png'
copyright                   : "2021"  # Copyright year to be placed in the footer

# Information about where the book exists on the web
description: >-
  A look at using jupyter-book for the uninitiated

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar       : true
  use_edit_page_button      : false # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  extra_navbar              : "" #Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer              : <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Kicking the Tires on Jupyter-Book</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="https://skyrockmoon.github.io/jb-kick-tires" property="cc:attributionName" rel="cc:attributionURL">Ryan Lowe</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License</a>.<br />Based on a work at <a xmlns:dct="http://purl.org/dc/terms/" href="https://skyrockmoon.github.io/jb-kick-tires" rel="dct:source">https://skyrockmoon.github.io/jb-kick-tires</a>. <br><br>Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the footer.
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  baseurl                   : https://skyrockmoon.github.io/jb-kick-tires  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis              : false
    utterances:
      repo: "SkyRockMoon/jb-kick-tires"


# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/SkyRockMoon/jb-kick-tires
  path_to_book                : "book"

# # binder:
# #   binderhub_url               : "https://mybinder.org"
# #   text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex

#######################################################################################
# Parse settings
parse:
  myst_extended_syntax: true